name: random_color
description: Generate random colors from hue, saturation and brightness that are visualy appearing. You can chose exact color specifications.
version: 1.0.6-nullsafety
homepage: https://github.com/knezzz/RandomColor

environment:
  sdk: ">=2.12.0-133.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: